require 'clearance/test/functional/confirmations_controller_test'
require 'clearance/test/functional/passwords_controller_test'
require 'clearance/test/functional/sessions_controller_test'
require 'clearance/test/functional/users_controller_test'
require 'clearance/test/test_helper'
require 'clearance/test/unit/clearance_mailer_test'
require 'clearance/test/unit/user_test'
